{% set name = "oxipng" %}
{% set version = "9.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shssoichiro/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 90c5e32c556c49e8fb2170f281586e87f7619fd574b4ccf1bc76e2f6819bba77

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - oxipng --version

about:
  home: https://github.com/shssoichiro/oxipng
  summary: 'Multithreaded PNG optimizer written in Rust'
  description: 'Oxipng is a multithreaded lossless PNG/APNG compression optimizer. It can be used via a command-line interface or as a library in other Rust programs.'
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
