{% set name = "oxipng" %}
{% set version = "9.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/shssoichiro/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8eae13e5aa6f500b231b4d15b9fefdeb5f6cc566ddab959b9b7a03a00bb3a520

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - oxipng --version

about:
  home: https://github.com/shssoichiro/oxipng
  summary: 'Multithreaded PNG optimizer written in Rust'
  description: 'Oxipng is a multithreaded lossless PNG/APNG compression optimizer. It can be used via a command-line interface or as a library in other Rust programs.'
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY_LICENSES.yaml

extra:
  recipe-maintainers:
    - freundTech
